// allow: SIZE_OK — declarative MCP tool schema table.
export const TOOLS = [
  {
    name: "lcm_health",
    title: "LCM Health",
    description: "Compatibility tool; prefer lcm_stats for health and aggregate index diagnostics.",
    inputSchema: { type: "object", properties: {} },
    annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  },
  {
    name: "lcm_stats",
    title: "LCM Stats",
    description: "Report aggregate LCM index shape, summary depths, graph counts, and freshness without raw transcript text.",
    inputSchema: { type: "object", properties: {} },
    annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  },
  {
    name: "lcm_list_sessions",
    title: "LCM List Sessions",
    description: "List sessions across projects with time, root/child, pagination, and optional compact summary filters.",
    inputSchema: {
      type: "object",
      properties: {
        since: { type: "string" },
        until: { type: "string" },
        cwd: { type: "string" },
        repoRoot: { type: "string" },
        parentSessionId: { type: "string" },
        rootsOnly: { type: "boolean", default: false },
        includeSummaries: { type: "boolean", default: false, description: "Include compact titles, overviews, prompts, outcomes, and topics in this one response." },
        limit: { type: "number", default: 50 },
        cursor: { type: "string" },
      },
    },
    annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  },
  {
    name: "lcm_usage",
    title: "LCM Usage",
    description: "Aggregate captured Codex token usage across filtered sessions. With rootsOnly, selected roots include all descendant sessions.",
    inputSchema: {
      type: "object",
      properties: {
        since: { type: "string" },
        until: { type: "string" },
        cwd: { type: "string" },
        repoRoot: { type: "string" },
        parentSessionId: { type: "string" },
        rootsOnly: { type: "boolean", default: false },
      },
    },
    annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  },
  {
    name: "lcm_grep",
    title: "LCM Grep",
    description: "Preferred standard workflow step 1 (grep): find relevant sessions in indexed memory, or search bounded sanitized overflow payloads when contentScope is overflow or both. Codex may surface this tool as mcp__codex_lcm__lcm_grep.",
    inputSchema: {
      type: "object",
      properties: {
        query: { type: "string" },
        limit: { type: "number", default: 10 },
        cwd: { type: "string" },
        repoRoot: { type: "string" },
        contentScope: { type: "string", enum: ["memory", "overflow", "both"], default: "memory" },
        excludeCurrentSession: { type: "boolean", default: false },
        excludeSessionIds: { type: "array", items: { type: "string" } },
      },
    },
    annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  },
  {
    name: "lcm_describe",
    title: "LCM Describe",
    description: "Preferred standard workflow step 2 (describe): inspect a session, summary node, or file reference, including summary-node depth and source lineage metadata. Codex may surface this tool as mcp__codex_lcm__lcm_describe.",
    inputSchema: {
      type: "object",
      properties: {
        sessionId: { type: "string" },
        nodeId: { type: "string" },
        fileId: { type: "string" },
        limit: { type: "number", default: 50 },
        offset: { type: "number", default: 0, description: "Byte offset when reading an overflow reference." },
        maxBytes: { type: "number", minimum: 4, maximum: 524288, default: 65536, description: "Maximum bytes to read from an overflow reference." },
        includeLineage: { type: "boolean", default: false, description: "Include full source ID arrays instead of compact source counts." },
      },
    },
    annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  },
  {
    name: "lcm_expand",
    title: "LCM Expand",
    description: "Preferred standard workflow step 3 (expand): expand one summary node into bounded source summary nodes and high-signal source events. Codex may surface this tool as mcp__codex_lcm__lcm_expand.",
    inputSchema: {
      type: "object",
      properties: {
        nodeId: { type: "string" },
        query: { type: "string" },
        limit: { type: "number", default: 4 },
      },
      required: ["nodeId"],
    },
    annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  },
  {
    name: "lcm_expand_query",
    title: "LCM Expand Query",
    description: "Find matching summary nodes and recursively expand their source lineage into bounded evidence for a focused query.",
    inputSchema: {
      type: "object",
      properties: {
        query: { type: "string" },
        cwd: { type: "string" },
        repoRoot: { type: "string" },
        sessionIds: { type: "array", items: { type: "string" } },
        budgetTokens: { type: "number", default: 2000 },
        limit: { type: "number", default: 4 },
        sourceLimit: { type: "number", default: 6, description: "Maximum source events or source summary nodes considered per matched node." },
        overview: { type: "boolean", default: false, description: "Prefer higher-depth, source-rich summary nodes for broad overview queries." },
      },
      required: ["query"],
    },
    annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  },
  {
    name: "lcm_context_plan",
    title: "LCM Context Plan",
    description: "Estimate recent-session token pressure and report compaction proximity. Returns diagnostics only; Codex owns compaction.",
    inputSchema: {
      type: "object",
      properties: {
        sessionId: { type: "string" },
        cwd: { type: "string" },
        repoRoot: { type: "string" },
        modelContextWindow: { type: "number", default: 128000 },
        autoCompactTokenLimit: { type: "number", default: 96000 },
        recentEventLimit: { type: "number", default: 80 },
        canControlCompaction: {
          type: "boolean",
          const: false,
          default: false,
          description: "Always false; this tool reports context pressure but cannot own Codex compaction.",
        },
      },
    },
    annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  },
  {
    name: "lcm_current_session",
    title: "LCM Current Session",
    description: "Find the current or latest known session by session ID, cwd, or repo root.",
    inputSchema: {
      type: "object",
      properties: {
        sessionId: { type: "string" },
        cwd: { type: "string" },
        repoRoot: { type: "string" },
      },
    },
    annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  },
  {
    name: "lcm_search_sessions",
    title: "LCM Search Sessions",
    description: "Compatibility tool; prefer lcm_grep with contentScope set to memory.",
    inputSchema: {
      type: "object",
      properties: {
        query: { type: "string" },
        limit: { type: "number", default: 10 },
        cwd: { type: "string" },
        repoRoot: { type: "string" },
        excludeCurrentSession: { type: "boolean", default: false },
        excludeSessionIds: { type: "array", items: { type: "string" } },
      },
    },
    annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  },
  {
    name: "lcm_get_session",
    title: "LCM Get Session",
    description: "Retrieve sanitized raw events for a session, optionally paged for long sessions.",
    inputSchema: {
      type: "object",
      properties: {
        sessionId: { type: "string" },
        limit: { type: "number" },
        cursor: { type: "string" },
      },
      required: ["sessionId"],
    },
    annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  },
  {
    name: "lcm_get_session_summary",
    title: "LCM Get Session Summary",
    description: "Compatibility tool; prefer lcm_describe with sessionId.",
    inputSchema: {
      type: "object",
      properties: {
        sessionId: { type: "string" },
      },
      required: ["sessionId"],
    },
    annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  },
  {
    name: "lcm_get_session_graph",
    title: "LCM Get Session Graph",
    description: "Retrieve a bounded DAG slice for a session, including session, turn, event, checkpoint, and summary nodes.",
    inputSchema: {
      type: "object",
      properties: {
        sessionId: { type: "string" },
        limit: { type: "number", default: 200 },
      },
      required: ["sessionId"],
    },
    annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  },
  {
    name: "lcm_get_recent_context",
    title: "LCM Get Recent Context",
    description: "Retrieve recent events for a session or latest cwd-matching session.",
    inputSchema: {
      type: "object",
      properties: {
        sessionId: { type: "string" },
        cwd: { type: "string" },
        repoRoot: { type: "string" },
        limit: { type: "number", default: 20 },
      },
    },
    annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  },
  {
    name: "lcm_pack_context",
    title: "LCM Pack Context",
    description: "Recover and resume prior Codex work after compaction, interruption, or handoff. Returns model-ready, token-budgeted Markdown from relevant session summaries and source evidence.",
    inputSchema: {
      type: "object",
      properties: {
        query: { type: "string" },
        sessionIds: { type: "array", items: { type: "string" } },
        budgetTokens: { type: "number", default: 1200 },
        cwd: { type: "string" },
      },
    },
    annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  },
  {
    name: "lcm_record_note",
    title: "LCM Record Note",
    description: "Record a user-authored note as a first-class LCM event.",
    inputSchema: {
      type: "object",
      properties: {
        sessionId: { type: "string" },
        cwd: { type: "string" },
        text: { type: "string" },
      },
      required: ["sessionId", "cwd", "text"],
    },
    annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  },
];
